# Generated by Django 4.2.7 on 2023-12-10 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dealer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'marketing_dealer',
            },
        ),
        migrations.CreateModel(
            name='DealerPrice',
            fields=[
                ('product_key', models.IntegerField(null=True)),
                ('price', models.FloatField(null=True)),
                ('product_url', models.URLField(primary_key=True, serialize=False, unique=True)),
                ('product_name', models.CharField(max_length=250)),
                ('date', models.DateField()),
                ('marking_date', models.DateTimeField(null=True)),
                ('dealer_id', models.ForeignKey(db_column='dealer_id', on_delete=django.db.models.deletion.CASCADE, related_name='dealer_prices', to='products.dealer')),
            ],
            options={
                'db_table': 'marketing_dealerprice',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('article', models.CharField(max_length=100, null=True)),
                ('ean_13', models.FloatField(null=True)),
                ('name', models.CharField(max_length=250)),
                ('cost', models.FloatField(null=True)),
                ('recommended_price', models.FloatField(null=True)),
                ('category_id', models.IntegerField(null=True)),
                ('ozon_name', models.CharField(max_length=250)),
                ('name_1c', models.CharField(max_length=250)),
                ('wb_name', models.CharField(max_length=250)),
                ('ozon_article', models.CharField(max_length=250)),
                ('wb_article', models.CharField(max_length=250)),
                ('ym_article', models.CharField(max_length=250)),
                ('wb_article_td', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'marketing_product',
            },
        ),
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('total_markup_count', models.IntegerField()),
                ('none_chosen_count', models.IntegerField()),
                ('choices_order', models.JSONField()),
                ('chosen_options_stats', models.JSONField()),
            ],
            options={
                'db_table': 'statistics',
            },
        ),
        migrations.CreateModel(
            name='ProductDealerKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choices_order', models.PositiveIntegerField(null=True)),
                ('marking_date', models.DateTimeField(null=True)),
                ('key', models.ForeignKey(db_column='key_id', on_delete=django.db.models.deletion.CASCADE, related_name='matching_products', to='products.dealerprice')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_dealer_keys', to='products.product')),
            ],
            options={
                'db_table': 'product_dealer_key',
            },
        ),
    ]
